baseURL = "https://jksntn.my.id/"
languageCode = "en-us"
title = "jksntn"

ignoreErrors = ["error-remote-getjson"]

disableHugoGeneratorInject = true
disableKinds = ["categories"]

enableRobotsTXT = true

paginate = 8
paginatePath = "p"

[outputs]
home = ["HTML","RSS"]

[params]

  [params.segment]
    id = "kUqH89S3AJWXRDFvqlkrcHDdWRLaZru2"
    
  [params.announcement]
    show = true

  [params.logo]
    mobile = "images/logo-mobile.svg"
    desktop = "images/logo.svg"
    desktop_height = "36px"
    desktop_width = "131px"
    alt = "Execute Big Pig"

  [params.homepage_meta_tags]
    meta_description = "Website personal dari seorang bapak-bapak fulltimer yang tinggal di Bekasi."
    meta_og_title = "jksntn"
    meta_og_type = "website"
    meta_og_url = "https://jksntn.my.id"
    meta_og_description = "Website personal dari seorang bapak-bapak fulltimer yang tinggal di Bekasi."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@jksntn"
    meta_twitter_creator = "@jksntn"

[menu]
  # Main Menu

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 1

  [[menu.main]]
      name = "Journals"
      url = "/journals/"
      weight = 3

  [[menu.main]]
      name = "Subscribe"
      url = "/subscribe"
      weight = 7

  # Footer Menu
      
  [[menu.about]]
      name = "Team"
      url = "/team/"
      weight = 1
  
  [[menu.about]]
      name = "Contact"
      url = "/contact/"
      weight = 2

  [[menu.about]]
      name = "Donate"
      url = "/donate/"
      weight = 3

  [[menu.about]]
    name = "Conduct"
    url = "/conduct/"
      weight = 4

  [[menu.about]]
    name = "Privacy"
    url = "/privacy/"
      weight = 5

  # Resources Menu
  
  [[menu.resources]]
    name = "Brand"
    url = "/brand/"
      weight = 1

  [[menu.resources]]
      name = "Transparency"
      url = "/transparency/"
      weight = 2
      
  [[menu.resources]]
      name = "Journals"
      url = "/journals/"
      weight = 4
      
  [[menu.resources]]
    name = "Press"
    url = "/press/"
      weight = 5

[taxonomies]
  journals_tags = "journals/tags"

[sitemap]
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2