baseURL = "https://jksntn.my.id/"
languageCode = "en-us"
title = "jksntn"

ignoreErrors = ["error-remote-getjson"]

disableHugoGeneratorInject = true
disableKinds = ["categories"]

enableRobotsTXT = true

paginate = 8
paginatePath = "p"

[outputs]
home = ["HTML","RSS"]

[params]

  [params.segment]
    id = "kUqH89S3AJWXRDFvqlkrcHDdWRLaZru2"
    
  [params.announcement]
    show = true

  [params.logo]
    mobile = "images/logo-mobile.svg"
    desktop = "images/logo.svg"
    desktop_height = "36px"
    desktop_width = "131px"
    alt = "Execute Big Pig"

  [params.homepage_meta_tags]
    meta_description = "Website personal dari seorang bapak-bapak fulltimer yang tinggal di Bekasi."
    meta_og_title = "jksntn"
    meta_og_type = "website"
    meta_og_url = "https://jksntn.my.id"
    meta_og_image = "images/personal/featured.png"
    meta_og_description = "Website personal dari seorang bapak-bapak fulltimer yang tinggal di Bekasi."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@jksntn"
    meta_twitter_creator = "@jksntn"

[menu]
  # Main Menu

  [[menu.main]]
      name = "Beranda"
      url = "/"
      weight = 1

  [[menu.main]]
      name = "Tentang"
      url = "/tentang/"
      weight = 2

  [[menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 3

  [[menu.main]]
      name = "Project"
      url = "/Project/"
      weight = 4      


  # Footer Menu
      
  [[menu.about]]
      name = "Tentang"
      url = "/tentang/"
      weight = 1
  
  [[menu.about]]
      name = "Blog"
      url = "/blog/"
      weight = 2

  [[menu.about]]
      name = "Project"
      url = "/project/"
      weight = 3

# Product Menu
  
  [[menu.product]]
    name = "Web Development"
    url = "#"
    weight = 1
      
  [[menu.product]]
    name = "Graphic Design"
    url = "#"
    weight = 2

  [[menu.product]]
    name = "Digital Marketing"
    url = "#"
    weight = 3    

  # Resources Menu
  
  [[menu.resources]]
    name = "Freebies"
    url = "#"
      weight = 1

  [[menu.resources]]
      name = "Books"
      url = "#"
      weight = 2
      
  [[menu.resources]]
      name = "Street Photography"
      url = "#"
      weight = 4
      
  [[menu.resources]]
    name = "Marketing"
    url = "#"
      weight = 5

  # Menu Hubungi Saya
  
  [[menu.hubungisaya]]
    name = "Twitter"
    url = "https://twitter.com/jksntn/"
      weight = 1

  [[menu.hubungisaya]]
      name = "Threads"
      url = "https://threads.net/jksntn/"
      weight = 2
      
  [[menu.hubungisaya]]
      name = "Facebook"
      url = "https://facebook.com/jksntn/"
      weight = 4

[taxonomies]
  blog_tags = "blog/tags"

[sitemap]
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Related

[related]
  threshold = 0 
  includeNewer = true
  toLower = false

  [[related.indices]]
      name = "tags"
      weight = 1

  [[related.indices]]
    name = "categories"
    weight = 2    

  [[related.indices]]
      name = "date"
      weight = 3